[package]
name = "mimalloc-test"
version = "0.1.0"
edition = "2021"

[dependencies]
libmimalloc-sys = { version = "0.1.40", package = "libmimalloc-sys-rspack", features = [
  "extended",
] }
mimalloc = { version = "0.1.44", package = "mimalloc-rspack" }

rspack = { path = "/home/user/projects/rspack/crates/rspack" }
rspack_core = { path = "/home/user/projects/rspack/crates/rspack_core/" }
rspack_regex = { path = "/home/user/projects/rspack/crates/rspack_regex/" }
rspack_macros = { path = "/home/user/projects/rspack/crates/rspack_macros" }
rspack_error = { path = "/home/user/projects/rspack/crates/rspack_error" }
rspack_loader_swc = { path = "/home/user/projects/rspack/crates/rspack_loader_swc/" }
rspack_hook = { path = "/home/user/projects/rspack/crates/rspack_hook/" }

stats_alloc = { version = "0.1.10", features = ["nightly"] }

serde_json = "*"
tokio = { version = "1", features = ["full"] }

[profile.release]
debug = true
strip = false
